### ISSUE TITLE
invalidating cache while new albums are found leads to NPE

### ISSUE THREAD

**Issue by xtj-9182** [garretyoder/Cluttr#3]
How to reproduce ?

1. exclude a folder
2. this will invalidate the caches
3. while new albums are found exclude another folder
4. repeat step 3 one time
4. NPE

stack trace:
09-11 17:08:14.571 28600-28600/org.polaric.cluttr E/Cluttr: Invalidate called, all caches will be wiped
09-11 17:08:14.590 28600-31245/org.polaric.cluttr E/Cluttr: A fatal error has occured during media loading, cache will be wiped
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmList org.polaric.cluttr.data.Album.getMedia()' on a null object reference
                                                                at org.polaric.cluttr.io.MediaLoader.updateSingleCover(MediaLoader.java:210)
                                                                at org.polaric.cluttr.io.MediaLoader.recursiveLoadAlbums(MediaLoader.java:113)
                                                                at org.polaric.cluttr.io.MediaLoader.recursiveLoadAlbums(MediaLoader.java:121)
                                                                at org.polaric.cluttr.io.MediaLoader.recursiveLoadAlbums(MediaLoader.java:121)
                                                                at org.polaric.cluttr.io.MediaLoader.recursiveLoadAlbums(MediaLoader.java:121)
                                                                at org.polaric.cluttr.io.MediaLoader.recursiveLoadAlbums(MediaLoader.java:121)
                                                                at org.polaric.cluttr.io.MediaLoader.access$200(MediaLoader.java:25)
                                                                at org.polaric.cluttr.io.MediaLoader$1.call(MediaLoader.java:46)
                                                                at org.polaric.cluttr.io.MediaLoader$1.call(MediaLoader.java:30)
                                                                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                                                                at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                                                                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by garretyoder** [comment]
Nice catch. Will fix in the next release.
